# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba404c017028315b87dbd592b14abf07b6c454c03249bbf13ac5e3441b698ad9f6ed7745d2388f662164d875d59f43df871aaa0036980eb7cc3102a2dec838a7

test:
  secret_key_base: f43da40d67a42434b30faf3961c5d3f400822b1b552804a37a7cd167c4a005a1f6ee376dc870293b82a0430ca77ae526d7e8f3c4f7732b6a3c5358bd1c19c48a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
